services:
  web:
    image: mlubert/clusteriomaster
    ports:
      - "12346:12345"
    volumes:
      - factorio:/clusterio/factorio
      - mods:/clusterio/sharedMods
    env_file:
      -  factorio.env
  ofsm:
    image: ofsm/ofsm:latest
    ports: 
      - "81:80"
    volumes:
      - factorio:/opt/factorio
      - mods:/opt/factorio/mods
    env_file:
      - ofsm.env

volumes:
  factorio:
  mods:
